name: learn-github-actions-CI-CD
on: [push]
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn
      - run: yarn start
  two:
    runs-on: ubuntu-latest
    needs: [one]
    steps:
      - run: yarn test1
